server:
  port: 1234
  log:
    level: debug

auth:
  base: http://localhost:8080
  issuer: http://localhost:8080/auth/realms/chatty-realm
  client_id: chatty
  secret: zQYJzWA588iivYVspQCzi8S2BwwdOpxf

database:
  password: postgres
